name: Test App

on: 
  push:
    branches:
      - master
      - sasi
      - Marco 
      - Bart
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        - name: Add conda to system path
          run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            echo $CONDA/bin >> $GITHUB_PATH
        - name: Install dependencies
          run: |
            conda env create -f environment.yml

        - name: Test with pytest
          run: |
            pytest
